/**:
  user_command_node:
    ros__parameters:
      pub_freq: 160.0
      local_ip: "0.0.0.0"
      local_port: 8890
      sender_ip: "192.168.19.93"
      sender_port: 8888
      heartbeat_hz: 2.0
      cmd_timeout_sec: 0.3
      body_height: 0.2
      fsm_mode: "transform_up"
      require_init_packet: false
      enable_cmd_limit: true
      max_linear_speed: 3.0
      max_angular_speed: 6.0
