#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SERVICE_NAME="user-command"
SERVICE_USER="root"
WS_DIR="/root/udp_ws"
ROS_DISTRO_NAME="humble"
ROS_DOMAIN_ID_VALUE="88"
ROS_LOCALHOST_ONLY_VALUE="0"
NODE_NAMESPACE="/"
IFACE_NAME="eth1"
IP_PREFIX="192.168.19."
ENABLE_NOW="false"

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --ws <path>              Workspace root path (default: ${WS_DIR})
  --service-name <name>    systemd service name (default: ${SERVICE_NAME})
  --user <name>            Service user (default: ${SERVICE_USER})
  --ros-distro <name>      ROS distro name (default: ${ROS_DISTRO_NAME})
  --ros-domain-id <id>     ROS_DOMAIN_ID value (default: ${ROS_DOMAIN_ID_VALUE})
  --localhost-only <0|1>   ROS_LOCALHOST_ONLY value (default: ${ROS_LOCALHOST_ONLY_VALUE})
  --namespace <ns>         ROS node namespace (default: ${NODE_NAMESPACE})
  --iface <name>           Network interface check in ExecStartPre (default: ${IFACE_NAME})
  --ip-prefix <prefix>     IPv4 prefix check in ExecStartPre (default: ${IP_PREFIX})
  --enable-now             Enable and start service immediately
  -h, --help               Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ws) WS_DIR="$2"; shift 2 ;;
    --service-name) SERVICE_NAME="$2"; shift 2 ;;
    --user) SERVICE_USER="$2"; shift 2 ;;
    --ros-distro) ROS_DISTRO_NAME="$2"; shift 2 ;;
    --ros-domain-id) ROS_DOMAIN_ID_VALUE="$2"; shift 2 ;;
    --localhost-only) ROS_LOCALHOST_ONLY_VALUE="$2"; shift 2 ;;
    --namespace) NODE_NAMESPACE="$2"; shift 2 ;;
    --iface) IFACE_NAME="$2"; shift 2 ;;
    --ip-prefix) IP_PREFIX="$2"; shift 2 ;;
    --enable-now) ENABLE_NOW="true"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ ! -d "${WS_DIR}" ]]; then
  echo "Workspace path not found: ${WS_DIR}" >&2
  exit 1
fi

START_SCRIPT_DST="/usr/local/bin/start_user_command.sh"
ENV_FILE="/etc/default/${SERVICE_NAME}"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

install -m 0755 "${REPO_ROOT}/scripts/start_user_command.sh" "${START_SCRIPT_DST}"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by install_user_command_service.sh
WS_DIR=${WS_DIR}
ROS_DISTRO_NAME=${ROS_DISTRO_NAME}
ROS_DOMAIN_ID_VALUE=${ROS_DOMAIN_ID_VALUE}
ROS_LOCALHOST_ONLY_VALUE=${ROS_LOCALHOST_ONLY_VALUE}
NODE_NAMESPACE=${NODE_NAMESPACE}
EOF

cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=ROS2 user_command autostart
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=${SERVICE_USER}
WorkingDirectory=/root
EnvironmentFile=-${ENV_FILE}
ExecStartPre=/bin/bash -lc 'for i in {1..30}; do ip -4 addr show ${IFACE_NAME} | grep -q "inet ${IP_PREFIX}" && exit 0; sleep 1; done; exit 1'
ExecStart=${START_SCRIPT_DST}
Restart=always
RestartSec=2
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service"

if [[ "${ENABLE_NOW}" == "true" ]]; then
  systemctl restart "${SERVICE_NAME}.service"
fi

echo "Installed:"
echo "  Service file: ${SERVICE_FILE}"
echo "  Env file:     ${ENV_FILE}"
echo "  Start script: ${START_SCRIPT_DST}"
echo
echo "Next commands:"
echo "  sudo systemctl status ${SERVICE_NAME}.service"
echo "  sudo journalctl -u ${SERVICE_NAME}.service -f"

