from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        Node(
            package='dog_udp_comm',
            executable='tracking_string_bridge.py',
            name='tracking_string_bridge',
            output='screen',
            parameters=[
                {'tracking_topic': '/tracking'},
                {'state_topic': '/tracking_state'},
                {'pixel_topic': '/tracking_pixel'},
                {'image_width': 640.0},
                {'image_height': 480.0},
                {'max_allowed_age_ms': 500.0},
                {'max_consecutive_drop': 3},
                {'warn_interval_sec': 1.0},
                {'use_source_timestamp_for_header': True},
                {'topic_check_period_sec': 0.5},
                {'tracking_topic_lost_timeout_sec': 1.0},
            ],
        ),
        Node(
            package='dog_udp_comm',
            executable='pixel_to_scan_polar.py',
            name='pixel_to_scan_polar',
            output='screen',
            parameters=[
                {'scan_topic': '/scan'},
                {'pixel_topic': '/tracking_pixel'},
                {'out_topic': '/person_polar'},
                {'fx': 600.0},
                {'cx': 320.0},
                {'yaw_cam_to_lidar': 0.0},
                {'search_half_window': 6},
                {'range_min_valid': 0.10},
                {'range_max_valid': 10.0},
                {'publish_debug': False},
            ],
        ),
        Node(
            package='dog_udp_comm',
            executable='sender_node',
            name='udp_cmd_vel_server',
            output='screen',
            parameters=[
                {'local_ip': '0.0.0.0'},
                {'local_port': 8888},
            ],
        ),
        Node(
            package='dog_udp_comm',
            executable='host_mpc_controller.py',
            name='host_mpc_controller',
            output='screen',
            parameters=[
                {'person_topic': '/person_polar'},
                {'tracking_state_topic': '/tracking_state'},
                {'cmd_topic': '/track_cmd_vel'},
                {'control_hz': 30.0},
                {'dt': 0.0},
                {'horizon': 12},
                {'msg_timeout': 0.2},
                {'tracking_state_timeout_sec': 0.2},
                {'require_first_tracking_frame': True},
                {'desired_distance': 1.2},
                {'distance_tolerance': 0.08},
                {'angle_tolerance': 0.08},
                {'stop_when_aligned': True},
                {'stop_on_lost_target': True},
                {'allow_reverse': False},
                {'target_lost_duration_sec': 5.0},
                {'max_v': 0.8},
                {'max_w': 1.5},
                {'max_reverse_v': 0.2},
                {'q_dist': 16.0},
                {'q_angle': 10.0},
                {'r_v': 0.35},
                {'r_w': 0.25},
                {'qf_scale': 4.0},
                {'kff_dist': 0.9},
                {'kff_angle': 1.2},
                {'distance_filter_alpha': 0.65},
                {'angle_filter_alpha': 0.65},
                {'min_valid_distance': 0.15},
                {'max_valid_distance': 8.0},
            ],
        ),
    ])
